[2025-02-11T18:25:18.936+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T18:25:19.000+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_to_s3_pipeline.upload_to_s3 manual__2025-02-11T18:25:10.659164+00:00 [queued]>
[2025-02-11T18:25:19.010+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_to_s3_pipeline.upload_to_s3 manual__2025-02-11T18:25:10.659164+00:00 [queued]>
[2025-02-11T18:25:19.011+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-11T18:25:19.059+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2025-02-11 18:25:10.659164+00:00
[2025-02-11T18:25:19.092+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=117) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T18:25:19.106+0000] {standard_task_runner.py:72} INFO - Started process 118 to run task
[2025-02-11T18:25:19.114+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_to_s3_pipeline', 'upload_to_s3', 'manual__2025-02-11T18:25:10.659164+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/s3_data.py', '--cfg-path', '/tmp/tmp75vb9tzp']
[2025-02-11T18:25:19.119+0000] {standard_task_runner.py:105} INFO - Job 37: Subtask upload_to_s3
[2025-02-11T18:25:19.194+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_to_s3_pipeline.upload_to_s3 manual__2025-02-11T18:25:10.659164+00:00 [running]> on host 26951f9d626e
[2025-02-11T18:25:19.269+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_to_s3_pipeline' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T18:25:10.659164+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T18:25:10.659164+00:00'
[2025-02-11T18:25:19.271+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-11T18:25:19.289+0000] {s3_data.py:28} INFO - Uploading nba.sqlite to S3 bucket capstone*** at nba_data/nba.sqlite
[2025-02-11T18:25:20.147+0000] {s3_data.py:39} ERROR - Error uploading to S3: [Errno 2] No such file or directory: '/opt/***/data/nba.sqlite'
[2025-02-11T18:25:20.150+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-11T18:25:20.193+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-11T18:25:20.194+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=kaggle_to_s3_pipeline, task_id=upload_to_s3, run_id=manual__2025-02-11T18:25:10.659164+00:00, execution_date=20250211T182510, start_date=20250211T182519, end_date=20250211T182520
[2025-02-11T18:25:20.298+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T18:25:20.332+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T18:25:20.336+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
